version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads  # Mount the uploads directory to persist uploaded files